apiVersion: v2
name: grafana-wrapper
description: Wrapper for official Grafana Helm Chart
version: 1.0.0
dependencies:
  - name: grafana
    version: 10.4.0
    repository: https://grafana.github.io/helm-charts