configs:
  params:
    server.insecure: "true"

server:
  service:
    type: NodePort
    nodePortHttp: 30083
    nodePortHttps: 30445

repoServer:
  volumes:
    - name: repo-cache
      persistentVolumeClaim:
        claimName: argocd-repo-server-cache
  volumeMounts:
    - name: repo-cache
      mountPath: /app/config/reposerver

  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: argocd-repo-server
              app.kubernetes.io/instance: argocd
          topologyKey: kubernetes.io/hostname

redis:
  enabled: true
  persistence:
    enabled: true
    size: 5Gi
    storageClass: longhorn


